# Generated by Django 5.0.7 on 2024-08-16 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=150)),
                ('barangay', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MOA',
            fields=[
                ('moaID', models.AutoField(primary_key=True, serialize=False)),
                ('partyADescription', models.CharField()),
                ('partyBDescription', models.CharField()),
                ('termination', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Effectivity',
            fields=[
                ('effectivityID', models.AutoField(primary_key=True, serialize=False)),
                ('effectivity', models.TextField()),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.moa')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAgency',
            fields=[
                ('agencyID', models.AutoField(primary_key=True, serialize=False)),
                ('agencyName', models.CharField(max_length=150)),
                ('addressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='PartyObligation',
            fields=[
                ('poID', models.AutoField(primary_key=True, serialize=False)),
                ('obligation', models.TextField()),
                ('party', models.TextField()),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.moa')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('programCategory', models.CharField(max_length=150)),
                ('projectTitle', models.CharField(max_length=150)),
                ('projectType', models.CharField(max_length=150)),
                ('projectCategory', models.CharField(max_length=150)),
                ('researchTitle', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('accreditationLevel', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('targetImplementation', models.DateField()),
                ('totalHours', models.FloatField()),
                ('background', models.CharField(max_length=150)),
                ('projectComponent', models.CharField(max_length=150)),
                ('beneficiaries', models.CharField(max_length=150)),
                ('totalBudget', models.IntegerField()),
                ('agencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.partneragency')),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.moa')),
                ('projectLocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringPlanAndSchedule',
            fields=[
                ('MPASID', models.AutoField(primary_key=True, serialize=False)),
                ('approach', models.TextField()),
                ('dataGatheringStrategy', models.TextField()),
                ('schedule', models.TextField()),
                ('implementationPhase', models.TextField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingOfTrainers',
            fields=[
                ('LOTID', models.AutoField(primary_key=True, serialize=False)),
                ('trainingLoad', models.CharField(max_length=300)),
                ('hours', models.FloatField()),
                ('ustpBudget', models.IntegerField()),
                ('agencyBudget', models.IntegerField()),
                ('totalBudgetRequirement', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='GoalsAndObjectives',
            fields=[
                ('GOAID', models.AutoField(primary_key=True, serialize=False)),
                ('goalsAndObjectives', models.TextField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAndMonitoring',
            fields=[
                ('EAMID', models.AutoField(primary_key=True, serialize=False)),
                ('projectSummary', models.TextField()),
                ('indicators', models.TextField()),
                ('meansOfVerification', models.TextField()),
                ('RisksAssumptions', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRequirementsItems',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=150)),
                ('ustpAmount', models.IntegerField()),
                ('partnerAmount', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivities',
            fields=[
                ('projectActivitiesID', models.AutoField(primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('involved', models.TextField()),
                ('targetDate', models.DateField()),
                ('personResponsibleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Proponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectLead', models.BooleanField(default=False)),
                ('programChair', models.BooleanField(default=False)),
                ('collegeDean', models.BooleanField(default=False)),
                ('ECRDirector', models.BooleanField(default=False)),
                ('VCAA', models.BooleanField(default=False)),
                ('VCRI', models.BooleanField(default=False)),
                ('accountant', models.BooleanField(default=False)),
                ('chancellor', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signatories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvalStatus', models.BooleanField(default=False)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('targetGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('targetGroup', models.CharField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Witnesseth',
            fields=[
                ('witnessethID', models.AutoField(primary_key=True, serialize=False)),
                ('whereas', models.TextField()),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docquestapp.moa')),
            ],
        ),
    ]
