# Generated by Django 5.0.7 on 2024-08-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='id',
        ),
        migrations.AlterField(
            model_name='roles',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
