# Generated by Django 5.0.7 on 2024-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='targetScope',
            field=models.TextField(),
        ),
    ]
