# Generated by Django 5.0.7 on 2024-09-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='moaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectMoa', to='docquestapp.moa'),
        ),
    ]
