# Generated by Django 5.0.7 on 2024-08-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0002_remove_roles_id_alter_roles_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationandmonitoring',
            old_name='RisksAssumptions',
            new_name='risksAssumptions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='campus',
            field=models.CharField(default='NO CAMPUS SELECTED', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.CharField(default='NO COLLEGE SELECTED', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contactNumber',
            field=models.CharField(default='NO NUMBER', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='NO DEPARTMENT SELECTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middlename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moa',
            name='partyADescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moa',
            name='partyBDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moa',
            name='termination',
            field=models.TextField(),
        ),
    ]
