# Generated by Django 5.0.7 on 2024-09-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0002_alter_project_moaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetrequirementsitems',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='evaluationandmonitoring',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='goalsandobjectives',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='loadingoftrainers',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='monitoringplanandschedule',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectactivities',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='proponents',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='signatories',
            old_name='projectID',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='targetgroup',
            old_name='projectID',
            new_name='project',
        ),
    ]
