# Generated by Django 5.0.7 on 2024-10-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0002_alter_project_targetscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivities',
            name='personResponsible',
            field=models.TextField(),
        ),
    ]
