# Generated by Django 5.0.7 on 2024-10-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0003_alter_projectactivities_personresponsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='indicators',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='meansOfVerification',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='projectSummary',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='risksAssumptions',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='evaluationandmonitoring',
            name='type',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
