# Generated by Django 5.0.7 on 2024-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0003_rename_risksassumptions_evaluationandmonitoring_risksassumptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequirementsitems',
            name='itemName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loadingoftrainers',
            name='trainingLoad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='accreditationLevel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='beneficiaries',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='college',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='programCategory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectComponent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='targetGroup',
            field=models.CharField(max_length=200),
        ),
    ]
