# Generated by Django 5.0.7 on 2024-10-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0004_rename_personresponsibleid_projectactivities_personresponsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='uniqueCode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
