# Generated by Django 5.0.7 on 2024-08-31 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0004_alter_budgetrequirementsitems_itemname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='moaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docquestapp.moa'),
        ),
    ]
