# Generated by Django 5.0.7 on 2024-10-17 01:32
from django.db import migrations
from django.utils import timezone

def set_default_date_created(apps, schema_editor):
    Project = apps.get_model('docquestapp', 'Project')
    Project.objects.all().update(dateCreated=timezone.now())  # or a specific date

class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0005_project_datecreated_project_status_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_date_created),
    ]
