# Generated by Django 5.0.7 on 2024-10-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0006_auto_20241017_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
