# Generated by Django 5.0.7 on 2024-11-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0023_alter_programchairapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moa',
            old_name='partyADescription',
            new_name='partyDescription',
        ),
        migrations.RemoveField(
            model_name='moa',
            name='partyBDescription',
        ),
    ]
