# Generated by Django 5.0.7 on 2024-12-01 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('docquestapp', '0025_alter_faculty_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moa',
            old_name='partyDescription',
            new_name='partyADescription',
        ),
        migrations.AddField(
            model_name='moa',
            name='partyBDescription',
            field=models.TextField(default='shhe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moa',
            name='partyCDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='previous_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docquestapp.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_stage',
            field=models.CharField(choices=[('director', 'Director Review'), ('vpala', 'VPALA Final Review')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('content_type', 'source_id', 'review_stage')},
        ),
    ]
