# Generated by Django 5.0.7 on 2024-12-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docquestapp', '0026_rename_partydescription_moa_partyadescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('thirdPartyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('moaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdParty', to='docquestapp.moa')),
            ],
        ),
    ]
